#!/usr/bin/env node

/**
 * Report Generator and Telegram Notifier
 * Creates detailed call reports and sends notifications
 */

import fetch from 'node-fetch';

export class Reporter {
  constructor(telegramToken, telegramChatId) {
    this.telegramToken = telegramToken;
    this.telegramChatId = telegramChatId;
  }

  generateReport(callData) {
    const {
      phoneNumber,
      businessName,
      task,
      status,
      duration,
      startTime,
      endTime,
      transcript,
      outcome,
      keyDetails,
      nextSteps,
      transcriptPath
    } = callData;

    const statusEmoji = status === 'completed' ? '✅' : 
                       status === 'failed' ? '❌' : 
                       status === 'voicemail' ? '📭' : '⚠️';

    const durationStr = this.formatDuration(duration);
    const timestampStr = new Date(startTime).toUTCString();

    return `# 📞 Call Report

## ${statusEmoji} ${businessName || 'Phone Call'}

**Status**: ${status.charAt(0).toUpperCase() + status.slice(1)}
**Phone**: ${phoneNumber}
**Duration**: ${durationStr}
**Time**: ${timestampStr}

---

## 🎯 Objective

${task}

---

## ${outcome ? '✅ Outcome' : '📋 Result'}

${outcome || 'Call did not complete successfully.'}

${keyDetails && keyDetails.length > 0 ? `
---

## 📝 Key Details

${keyDetails.map(detail => `- ${detail}`).join('\n')}
` : ''}

${nextSteps && nextSteps.length > 0 ? `
---

## 📌 Next Steps

${nextSteps.map(step => `- ${step}`).join('\n')}
` : ''}

---

## 💬 Conversation Summary

${this.generateConversationSummary(transcript)}

---

## 📄 Files

- Full transcript: \`${transcriptPath}\`
- Call recording: Available in same directory
- Structured data: \`summary.json\`

---

*Generated by thepopebot AI Phone Call skill*
`;
  }

  generateConversationSummary(transcript) {
    if (!transcript || transcript.length === 0) {
      return '_No conversation data available._';
    }

    const summary = transcript
      .slice(0, 10) // First 10 exchanges
      .map(msg => {
        const speaker = msg.role === 'assistant' ? '🤖 AI' : '👤 Human';
        const content = msg.content.length > 150 
          ? msg.content.substring(0, 150) + '...' 
          : msg.content;
        return `${speaker}: ${content}`;
      })
      .join('\n\n');

    if (transcript.length > 10) {
      return summary + `\n\n_... and ${transcript.length - 10} more exchanges. See full transcript for details._`;
    }

    return summary;
  }

  formatDuration(seconds) {
    if (!seconds) return '0:00';
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  }

  async sendTelegramNotification(callData) {
    if (!this.telegramToken || !this.telegramChatId) {
      console.warn('Telegram credentials not configured, skipping notification');
      return false;
    }

    const {
      phoneNumber,
      businessName,
      task,
      status,
      duration,
      outcome,
      keyDetails,
      transcriptPath
    } = callData;

    const statusEmoji = status === 'completed' ? '✅' : 
                       status === 'failed' ? '❌' : 
                       status === 'voicemail' ? '📭' : '⚠️';

    const durationStr = this.formatDuration(duration);
    const timestamp = new Date().toUTCString();

    let message = `📞 *Call Complete: ${this.escapeMarkdown(businessName || 'Unknown')}*\n\n`;
    message += `${statusEmoji} *Status*: ${status}\n`;
    message += `📱 *Number*: ${phoneNumber}\n`;
    message += `⏱️ *Duration*: ${durationStr}\n`;
    message += `📅 *Time*: ${timestamp}\n\n`;

    message += `🎯 *Objective*:\n${this.escapeMarkdown(task.substring(0, 200))}\n\n`;

    if (outcome) {
      message += `${status === 'completed' ? '✅' : '📋'} *Outcome*:\n${this.escapeMarkdown(outcome)}\n\n`;
    }

    if (keyDetails && keyDetails.length > 0) {
      message += `📝 *Key Details*:\n`;
      keyDetails.slice(0, 5).forEach(detail => {
        message += `• ${this.escapeMarkdown(detail)}\n`;
      });
      message += `\n`;
    }

    message += `💬 *Full transcript*:\n\`${transcriptPath}\``;

    try {
      const url = `https://api.telegram.org/bot${this.telegramToken}/sendMessage`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: this.telegramChatId,
          text: message,
          parse_mode: 'Markdown'
        })
      });

      if (!response.ok) {
        const error = await response.text();
        console.error('Telegram API error:', error);
        return false;
      }

      return true;
    } catch (error) {
      console.error('Failed to send Telegram notification:', error.message);
      return false;
    }
  }

  escapeMarkdown(text) {
    if (!text) return '';
    return text.replace(/([_*\[\]()~`>#+\-=|{}.!])/g, '\\$1');
  }

  extractKeyDetails(transcript, task) {
    // Extract important information from conversation
    const details = [];
    const keywords = [
      'appointment', 'reservation', 'booking', 'confirmed', 'confirmation',
      'time', 'date', 'location', 'address', 'phone', 'email',
      'price', 'cost', 'total', 'payment',
      'name', 'reference', 'number', 'id'
    ];

    transcript.forEach(msg => {
      if (msg.role === 'user') {
        keywords.forEach(keyword => {
          if (msg.content.toLowerCase().includes(keyword)) {
            // Extract sentence containing keyword
            const sentences = msg.content.split(/[.!?]/);
            const relevant = sentences.find(s => 
              s.toLowerCase().includes(keyword)
            );
            if (relevant && relevant.length < 200) {
              details.push(relevant.trim());
            }
          }
        });
      }
    });

    // Deduplicate and limit
    return [...new Set(details)].slice(0, 8);
  }

  determineOutcome(transcript, status) {
    if (status !== 'completed') {
      return this.getFailureMessage(status);
    }

    // Analyze transcript for outcome
    const lastMessages = transcript.slice(-5);
    const allText = lastMessages.map(m => m.content).join(' ').toLowerCase();

    // Look for success indicators
    if (allText.includes('confirmed') || allText.includes('booked') || 
        allText.includes('scheduled') || allText.includes('reservation')) {
      return 'Successfully completed the requested task. Details confirmed.';
    }

    if (allText.includes('callback') || allText.includes('call back')) {
      return 'Requested a callback. Awaiting response.';
    }

    if (allText.includes('not available') || allText.includes('no availability')) {
      return 'No availability at requested times. May need alternative options.';
    }

    return 'Call completed. See transcript for full details.';
  }

  getFailureMessage(status) {
    const messages = {
      'no_answer': 'No answer. May want to try again during business hours.',
      'busy': 'Line was busy. Suggest retrying in a few minutes.',
      'voicemail': 'Reached voicemail. Message left with callback information.',
      'failed': 'Call failed to connect. Verify phone number and try again.',
      'error': 'Technical error occurred during call. Check logs for details.'
    };

    return messages[status] || 'Call did not complete as expected.';
  }

  suggestNextSteps(transcript, status, outcome) {
    const steps = [];

    if (status === 'no_answer' || status === 'busy') {
      steps.push('Retry calling during business hours');
      steps.push('Try calling at a different time of day');
    }

    if (status === 'voicemail') {
      steps.push('Wait for callback from business');
      steps.push('Follow up if no response within 24 hours');
    }

    const allText = transcript.map(m => m.content).join(' ').toLowerCase();

    if (allText.includes('callback') || allText.includes('call back')) {
      steps.push('Wait for scheduled callback');
    }

    if (allText.includes('email') && !allText.includes('no email')) {
      steps.push('Check email for confirmation');
    }

    if (allText.includes('confirmation') && !allText.includes('no confirmation')) {
      steps.push('Save confirmation number/details');
    }

    if (outcome && outcome.includes('alternative') || allText.includes('instead')) {
      steps.push('Consider alternative options discussed');
    }

    // Default suggestions
    if (steps.length === 0 && status === 'completed') {
      steps.push('No further action required');
    }

    return steps;
  }
}
